#!/usr/bin/env bash
#Displays a list of current running process
#Must show all processes, for all users, including those which 
#+might not have a TTY

# Display header
echo "PID   PPID  CMD"
# Use ps command to display all processes with hierarchy
ps axo pid,ppid,cmd --forest